[features]
seeds = false
skip-lint = false
[programs.localnet]
two_sided_marketplace = "F5JwgWNNaiKCYGNGejY8MK5n6qhThmjjfNjKrsbs7T2E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sudhan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
